2021-05-15 09:24:39,115 INFO    MainThread:12206 [wandb_setup.py:_flush():69] setting env: {}
2021-05-15 09:24:39,115 INFO    MainThread:12206 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-15 09:24:39,115 INFO    MainThread:12206 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/code/wandb/run-20210515_092439-1bver30j/logs/debug.log
2021-05-15 09:24:39,115 INFO    MainThread:12206 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/code/wandb/run-20210515_092439-1bver30j/logs/debug-internal.log
2021-05-15 09:24:39,116 INFO    MainThread:12206 [wandb_init.py:init():369] calling init triggers
2021-05-15 09:24:39,116 INFO    MainThread:12206 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-15 09:24:39,116 INFO    MainThread:12206 [wandb_init.py:init():418] starting backend
2021-05-15 09:24:39,116 INFO    MainThread:12206 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-15 09:24:39,138 INFO    MainThread:12206 [backend.py:ensure_launched():132] starting backend process...
2021-05-15 09:24:39,155 INFO    MainThread:12206 [backend.py:ensure_launched():137] started backend process with pid: 12233
2021-05-15 09:24:39,157 INFO    MainThread:12206 [wandb_init.py:init():423] backend started and connected
2021-05-15 09:24:39,158 INFO    MainThread:12206 [wandb_init.py:init():465] updated telemetry
2021-05-15 09:24:39,159 INFO    MainThread:12206 [wandb_init.py:init():484] communicating current version
2021-05-15 09:24:40,374 INFO    MainThread:12206 [wandb_init.py:init():489] got version response 
2021-05-15 09:24:40,374 INFO    MainThread:12206 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-15 09:24:40,587 INFO    MainThread:12206 [wandb_init.py:init():522] starting run threads in backend
2021-05-15 09:24:45,261 INFO    MainThread:12206 [wandb_run.py:_console_start():1565] atexit reg
2021-05-15 09:24:45,262 INFO    MainThread:12206 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-15 09:24:45,262 INFO    MainThread:12206 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-15 09:24:45,265 INFO    MainThread:12206 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-15 09:24:45,265 INFO    MainThread:12206 [wandb_init.py:init():546] run started, returning control to user process
2021-05-15 09:24:50,091 INFO    MainThread:12206 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-15 09:24:50,095 INFO    MainThread:12206 [wandb_run.py:_restore():1507] restore
2021-05-15 09:24:52,313 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 504
  total_bytes: 504
}

2021-05-15 09:24:52,616 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 504
  total_bytes: 10004
}

2021-05-15 09:24:53,008 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9734
  total_bytes: 10004
}

2021-05-15 09:24:53,110 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9734
  total_bytes: 10004
}

2021-05-15 09:24:53,211 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10004
  total_bytes: 10004
}

2021-05-15 09:24:53,313 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10004
  total_bytes: 10004
}

2021-05-15 09:24:53,415 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10004
  total_bytes: 10004
}

2021-05-15 09:24:53,516 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10004
  total_bytes: 10004
}

2021-05-15 09:24:53,618 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10004
  total_bytes: 10004
}

2021-05-15 09:24:53,719 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10004
  total_bytes: 10004
}

2021-05-15 09:24:53,820 INFO    MainThread:12206 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10004
  total_bytes: 10004
}

2021-05-15 09:24:54,922 INFO    MainThread:12206 [wandb_run.py:_show_files():1879] logging synced files
